DPHGallery/Controllers/GalleryController.cs
using DPHGallery.Classes;
using DPHGallery.Models.ViewModels;
using DPHGallery.ORM.Contexts;
using DPHGallery.ORM.Entities;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Dynamic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace DPHGallery.Controllers
{
	[Authorize]
	public class GalleryController : Controller
	{
		public ActionResult Index()
		{
			ViewBag.Title = "Explore";

			var ctx = new GalleryContext();
			var imagesCollection = ctx.Images.ToList();

			return View(imagesCollection);
		}

		public ActionResult MyImages()
		{
			ViewBag.Title = "My images";

			var ctx = new GalleryContext();
			string userId = User.Identity.GetUserId();
			var user = ctx.Users.Where(x => x.Id == userId).First();
			var imagesCollection = ctx.Images
				.Where(x => x.OwnerId == user.Id)
				.ToList();
			
			return View(imagesCollection);
		}

		public ActionResult GetImage(string param)
		{
			string universalPath = Base64Utils.Decode(param);
			FileManager fm = new FileManager();
			Image img = fm.GetImage(universalPath);
			Stream stream = fm.ImageToStream(img);

			return base.File(stream, img.RawFormat.ToString());
		}

		public ActionResult FindSimilar(Guid param)
		{
			var ctx = new GalleryContext();
			var imagesCollection = ctx.Images.ToList();

			var img = imagesCollection.Find(x => x.Id == param);
			var similarImages = imagesCollection.Where(
				x =>
					x.Id != param
					&& HammingDistance.Calculate(
						(byte)img.DPH, (byte)x.DPH) <= 4
					)
				.OrderByDescending(
					x => HammingDistance.Calculate(
						(byte)img.DPH, (byte)x.DPH
					)
				)
				.ToList();

			var viewModel = new SimilarImagesViewModel()
			{
				SourceImage = img,
				SimilarImages = similarImages
			};

			return View(viewModel);
		}
	}
}

DPHGallery/Views/Gallery/FindSimilar.cshtml
@model DPHGallery.Models.ViewModels.SimilarImagesViewModel

<div class="row">
    <div class="col-md-12">
        <h2>Selected image:</h2>
        <hr />
        <div class="thumbnail">
            <img src="@Url.Action("GetImage", "Gallery", new { param = Model.SourceImage.ThumbnailPath })" alt="@Model.SourceImage.Description">
            <div class="caption">
                <p>Autor: @Model.SourceImage.Owner.UserName</p>
                <p>MD5: @Model.SourceImage.ImageHash</p>
                <p>DPH: @Model.SourceImage.DPH</p>
                <p>
                    <a href="@Url.Action("GetImage", "Gallery", new { param = Model.SourceImage.ImagePath })" class="btn btn-primary" role="button">Show</a>
                    <a href="#" class="btn btn-default" role="button">Find similar</a>
                </p>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <h2>Images similar to the selected one:</h2>
    <hr />
    @foreach (var image in Model.SimilarImages)
    {
        <div class="col-md-4">
            <div class="thumbnail">
                <img src="@Url.Action("GetImage", "Gallery", new { param = image.ThumbnailPath })" alt="@image.Description">
                <div class="caption">
                    <p>Author: @image.Owner.UserName</p>
                    <p>MD5: @image.ImageHash</p>
                    <p>DPH: @image.DPH</p>
                    <p>
                        <a href="@Url.Action("GetImage", "Gallery", new { param = image.ImagePath })" class="btn btn-primary" role="button">Show</a>
                    </p>
                </div>
            </div>
        </div>
    }
</div>

DPHGallery/Views/Gallery/Index.cshtml
@model IEnumerable<DPHGallery.ORM.Entities.ImageEntity>

<div class="row">
    <h2>Explore other users images!</h2>
    <hr />
    @foreach (var image in Model)
    {
        <div class="col-md-4">
            <div class="thumbnail">
                <img src="@Url.Action("GetImage", "Gallery", new { param = image.ThumbnailPath })" alt="@image.Description">
                <div class="caption">
                    <p>Autor: @image.Owner.UserName</p>
                    <p>MD5: @image.ImageHash</p>
                    <p>DPH: @image.DPH</p>
                    <p>
                        <a href="@Url.Action("GetImage", "Gallery", new { param = image.ImagePath })" class="btn btn-primary" role="button">Show</a>
                    </p>
                </div>
            </div>
        </div>
    }
</div>

DPHGallery/Views/Gallery/MyImages.cshtml
@model IEnumerable<DPHGallery.ORM.Entities.ImageEntity>

<div class="row">
    <h2>Uploaded images:</h2>
    <hr />
    @foreach (var image in Model)
    {
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <img src="@Url.Action("GetImage", "Gallery", new { param = image.ThumbnailPath })" alt="@image.Description">
                <div class="caption">
                    <p>Autor: @image.Owner.UserName</p>
                    <p>MD5: @image.ImageHash</p>
                    <p>DPH: @image.DPH</p>
                    <p>
                        <a href="@Url.Action("GetImage", "Gallery", new { param = image.ImagePath })" class="btn btn-primary" role="button">Show</a>
                        <a href="@Url.Action("FindSimilar", "Gallery", new { param = image.Id })" class="btn btn-default" role="button">Find similar</a>
                        <a href="#" class="btn btn-danger" role="button">Delete</a>
                    </p>
                </div>
            </div>
        </div>
    }
</div>